FROM php:7.2-fpm

RUN apt-get update && apt-get install -y libmcrypt-dev \
    libmagickwand-dev --no-install-recommends

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN pecl install imagick && docker-php-ext-enable imagick
RUN pecl install xdebug-2.6.0RC2 && docker-php-ext-enable xdebug
RUN docker-php-ext-install pdo_mysql

WORKDIR /html
